[workspace]
members = [
    "providers","utils",
    "ethers","macros",
    "parity/ethabi",
    # "parity/ethereum-types",
    # "parity/fixed-hash",
    # "parity/primitive-types",
    # "parity/uint"
]