[workspace]
members = [
    "providers",
    "ethers","macros",
    "parity/ethabi",
    "signer",
    "wallet",
    "types",
    "hash",
    # "parity/ethereum-types",
    # "parity/fixed-hash",
    # "parity/primitive-types",
    # "parity/uint"
]